tenancy_ocid        = "ocid1.tenancy.oc1.."
user_ocid           = "ocid1.user.oc1.."
compartment_ocid    = "ocid1.compartment.oc1.."
fingerprint         = "a6:"
private_key_path    = "/home/..."
ssh_authorized_keys = "/home/..."
